[package]
name = "sup3"
version = "0.1.0"
edition = "2021"
authors = ["Lindsay Roberts <os@lindsayr.com>"]
license = "MIT"
description = "A standalone S3 uploader"
repository = "https://github.com/lsr0/sup3"

[dependencies]
aws-config = "0.10"
aws-sdk-s3 = "0.10"
aws-types = "0.10"
aws-smithy-types = "0.40"
tokio = { "version" = "1", features = ["full"] }
clap = { "version" = "3", features = ["std", "color", "suggestions", "derive", "cargo", "unicode"] }
url = "2"
thiserror = "1"
futures = "0.3"

[profile.release]
opt-level = "s"

[profile.release-small]
inherits = "release"
strip = true
lto = true
