name: Standalone Binaries

on:
  push:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    env:
      ARTIFACT_NAME: 'sup3-${ runner.os }-${ runner.arch }'
    outputs:
      artifact_name: ${ env.ARTIFACT_NAME }
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install Rust Stable'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 'Build'
        run: |
          cargo build --profile release-small
          cargo install --profile release-small --path . --root artifacts

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${ env.ARTIFACT_NAME }
          path: artifacts/bin/sup3*

  ubuntu:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: 'sup3-${ runner.os }-${ runner.arch }'
    outputs:
      artifact_name: ${ env.ARTIFACT_NAME }
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install Rust Stable'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 'Build'
        run: |
          cargo build --profile release-small
          cargo install --profile release-small --path . --root artifacts

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${ env.ARTIFACT_NAME }
          path: artifacts/bin/sup3

  macos:
    runs-on: macos-latest
    env:
      ARTIFACT_NAME: 'sup3-${ runner.os }-${ runner.arch }'
    outputs:
      artifact_name: ${ env.ARTIFACT_NAME }
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install Rust Stable'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 'Build'
        run: |
          cargo build --profile release-small
          cargo install --profile release-small --path . --root artifacts

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${ env.ARTIFACT_NAME }
          path: artifacts/bin/sup3

