name: Standalone Binaries

on:
  push:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install Rust Stable'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 'Build'
        run: |
          cargo build --profile release-small

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: sup3_win-x86-64
          path: target/release-small/sup3

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install Rust Stable'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 'Build'
        run: |
          cargo build --profile release-small

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: sup3_ubuntu-latest-x86-64
          path: target/release-small/sup3

  macos:
    runs-on: macos-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install Rust Stable'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 'Build'
        run: |
          cargo build --profile release-small

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: sup3_macos-latest-x86-64
          path: target/release-small/sup3

