name: Standalone Binaries

on:
  push:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install Rust Stable'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 'Build'
        run: |
          cargo build --profile release-small
          cargo install --profile release-small --path . --root artifacts

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: sup3-${{ runner.os }}-${{ runner.arch }}
          path: artifacts/bin/sup3*

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install Rust Stable'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 'Build'
        run: |
          cargo build --profile release-small
          cargo install --profile release-small --path . --root artifacts

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: sup3-${{ runner.os }}-${{ runner.arch }}
          path: artifacts/bin/sup3

  macos:
    runs-on: macos-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install Rust Stable'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 'Build'
        run: |
          cargo build --profile release-small
          cargo install --profile release-small --path . --root artifacts

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: sup3-${{ runner.os }}-${{ runner.arch }}
          path: artifacts/bin/sup3

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [windows, ubuntu, macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: job_artifacts

      - name: Generate Release Files
        run: |
          mkdir release/
          chmod +x -R job_artifacts/*/sup3
          tar cfz release/macos-x64_64-$GITHUB_REF_NAME.tar.gz -C job_artifacts/macOS-X64 sup3
          tar cfz release/linux-x64_64-$GITHUB_REF_NAME.tar.gz -C job_artifacts/Linux-X64 sup3
          zip release/windows-x64_64-$GITHUB_REF_NAME.exe job_artifacts/Windows-X64/sup3.exe --junk-paths
          echo "::set-output name=release_files::$(find release -type f)"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: true
          files: release/*
          fail_on_unmatched_files: true
